version: '3.7'
services:
  rclone:
    image: rclone/rclone:1.51.0
    command: copy drive:/Docker-Server/ /data/
    restart: 'no'
    volumes:
      - type: bind
        source: $PWD/volumes/rclone/config
        target: /config/rclone
      - type: bind
        source: $PWD/volumes/rclone/drive
        target: /data
