version: '3.6'
services:
  registry:
    env_file:
      - .env
      - ../Envsubst/env/server.env
    image: registry:2.7
    restart: always
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ${PWD}/volumes/registry:/var/lib/registry
      - ${PWD}/certs:/certs
      - ${PWD}/auth:/auth
