version: '3.6'
services:
  minecraft:
    image: itzg/minecraft-server:latest
    restart: always
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      ENABLE_RCON: "false"
      VERSION: 1.14.4
    volumes:
      - ${PWD}/volumes/minecraft:/data
      - ${PWD}/envsubst-out/server.properties:/data/server.properties
